server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**,/users/{userId}/events/{eventId}/requests/**
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**