spring:
  application:
    name: main-service
  config:
    import: "configserver:"
    cloud:
      discovery:
        enabled: true
        serviceId: config-server
        fail-fast: true
        retry:
          useRandomPolicy: true
          max-interval: 6000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10

stats-server:
  url: ${STATS_SERVER_URL:http://localhost:9090}